"""add session_name to session_records

Revision ID: 2825153d16e2
Revises: 0388961efc90
Create Date: 2026-04-26 19:04:23.860701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2825153d16e2'
down_revision: Union[str, Sequence[str], None] = '0388961efc90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_records', sa.Column('session_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_records', 'session_name')
    # ### end Alembic commands ###
