"""add_run_status_and_tool_call_records

Revision ID: 9b0c8cf96dcd
Revises: 9f4a8b2c1d7e
Create Date: 2026-05-17 01:41:30.449127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b0c8cf96dcd'
down_revision: Union[str, Sequence[str], None] = '9f4a8b2c1d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_call_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('tool_call_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['session_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_call_records_run_id'), 'tool_call_records', ['run_id'], unique=False)
    op.add_column('session_runs', sa.Column('run_status', sa.String(), nullable=False, server_default='completed'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_runs', 'run_status')
    op.drop_index(op.f('ix_tool_call_records_run_id'), table_name='tool_call_records')
    op.drop_table('tool_call_records')
    # ### end Alembic commands ###
