"""add_workspace_fields

Revision ID: d31633edbcb1
Revises: 3ee053c3b0a9
Create Date: 2026-05-22 23:09:40.157149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd31633edbcb1'
down_revision: Union[str, Sequence[str], None] = '3ee053c3b0a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_path'), 'workspaces', ['path'], unique=True)
    # Note: workspace_path and workspace_name already physically exist in session_records 
    # from a previous partial transaction success. Skipping duplicate column addition.
    # op.add_column('session_records', sa.Column('workspace_path', sa.String(), nullable=True))
    # op.add_column('session_records', sa.Column('workspace_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_records', 'workspace_name')
    op.drop_column('session_records', 'workspace_path')
    op.drop_index(op.f('ix_workspaces_path'), table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
