"""add agent definitions

Revision ID: f4a7c707a285
Revises: 2825153d16e2
Create Date: 2026-04-27 16:27:32.200985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4a7c707a285'
down_revision: Union[str, Sequence[str], None] = '2825153d16e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_definitions',
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('definition_json', sa.Text(), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_index(op.f('ix_agent_definitions_agent_id'), 'agent_definitions', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_definitions_agent_id'), table_name='agent_definitions')
    op.drop_table('agent_definitions')
    # ### end Alembic commands ###
